### ISSUE TITLE
Plateau_Malagasy_plat1254 is missing

### ISSUE THREAD

**Issue by SamPassmore** [kinbank/kinbank#102]
We have metadata from Parabank suggesting that they have data for Plateau_Malagasy_plat1254 but we have no raw data for this languages. 

@SimonGreenhill do you know who would be best to contact about this?

**Comment by SimonGreenhill** [comment]
Hmm try emailing Wolfgang. I'm not sure what his github account is

**Comment by SamPassmore** [comment]
Should've checked the closed issues - this was already dealt with in #91
