### ISSUE TITLE
Missing MPEGkin languages

### ISSUE THREAD

**Issue by SamPassmore** [kinbank/kinbank#103]
Hi Josh, 

In this list of languages you sent me for MPEG (a while ago now) there are three languages that I don't have datafiles for. Do you have them by chance? 

awet1244
kama1372
mbya1239

**Comment by jtbirchall** [comment]
[kinterm-TP-mbya1239.xlsx](https://github.com/kinbank/kinbank/files/6576464/kinterm-TP-mbya1239.xlsx)
[kinterm-TP-kama1373.xlsx](https://github.com/kinbank/kinbank/files/6576465/kinterm-TP-kama1373.xlsx)
[kinterm-TP-awet1244.xlsx](https://github.com/kinbank/kinbank/files/6576469/kinterm-TP-awet1244.xlsx)

Hi Sam, here they are in xlsx. I must've mixed up the glottocodes for Kamayurá when I sent you the list. The TG language is kama1373. Kama1372 is from a different language family.
