### ISSUE TITLE
make install

### ISSUE THREAD

**Issue by SamPassmore** [kinbank/kinbank#11]
Just a note for future:

I had a problem with make install 
Specifically the line:
`./env/bin/cldfbench catconfig`

This gave me the error
`The 'openpyxl; python_version > "3.5" and extra == "excel"' distribution was not found and is required by cldfbench`

It seemed to be something to do with not having run this line manually before:
`cldfbench catconfig`

Prior to this I couldn't get past the error regardless of what order packages were installed, or not installed. 

Not sure what changes, but it did the trick!

**Comment by SimonGreenhill** [comment]
Hmm, a876460 should fix this now.
