### ISSUE TITLE
Website typo

### ISSUE THREAD

**Issue by catherinesheard** [kinbank/kinbank#121]
Putting this here on the theory that it will be easiest for Sam -- I imagine on the Kinbank website that the label "parent's and parent's siblings" should be instead "parents and parents' siblings"?

**Comment by SamPassmore** [comment]
Thanks, Catherine. 

The website is kept here:
https://github.com/SamPassmore/kinbank_website/

But it is probably more obvious to move it to the Kinbank repo, so I'll do that shortly, too.
