### ISSUE TITLE
Improve accessibility for colorblind users

### ISSUE THREAD

**Issue by sqiouyilu** [kinbank/kinbank#123]
Kinship diagrams currently code some information using only color. If a user is colorblind, prints a page in black and white, or has color filters on their screen, they will lose information from the diagrams.

Suggest combining cues to ensure information is retained across various color calibrations. cf. this guide: https://web.archive.org/web/20230324094425/https://jfly.uni-koeln.de/color/

**Comment by SamPassmore** [comment]
The website code is held here:
https://github.com/SamPassmore/kinbank_website
(which isn't ideal or obvious but I am going on holiday today and I don't have time to fix it). 

I will move this to an issue over there.
