### ISSUE TITLE
indo1316: grandfather

### ISSUE THREAD

**Issue by hartenthaler** [kinbank/kinbank#126]
On http://www.kinbank.net/languages/indo1316/ there is:
- father's father | nénék | nénék

But it should be 
- father's father | kakek | kakek
 
I don't know if there should be apostrophes). It is for the father's father and the mother's father.

**Comment by SamPassmore** [comment]
Thanks Hermann Hartenthaler. Do you have a source confirming this, or is it just your personal knowledge?

This data was contributed via someone's personal knowledge (i.e. rather than from a publication or dictionary), so it would be interesting to determine where this difference comes from.

**Comment by SamPassmore** [comment]
Ah I see now that nénék is for mother's mother and father's mother - so perhaps this is a coding mistake. 
Would that be how you see it Hermann?

**Comment by hartenthaler** [comment]
Yes. My source is my daughter, she is living at Bali and speaks Indonesian.

**Comment by SamPassmore** [comment]
I fixed this in the parabank collection under the commit SHA of 00e32d14df4987f6611357bad6007242d32d3866

It will perpetuate to the main dataset / website when it is next updated.
