### ISSUE TITLE
stan1295: wrong term for German "parent's parent"

### ISSUE THREAD

**Issue by hartenthaler** [kinbank/kinbank#129]
There is written:
> parent's parent | Großeltern, Opa

But "Opa" is wrong and has to be deleted, because "Opa" (in English: "Grandpa") is only a male parent's parent.

(source: German is my first language)

**Comment by SamPassmore** [comment]
Hi Hermann,

Thanks for your suggestion.
There seems to be some within language variation on this, so I won't make
this change.

See :
https://twitter.com/SamPassmore_/status/1694127475713073314?t=WzUUI6pNsMXGIxBYhe8Njg&s=19

Sam

**Comment by hartenthaler** [comment]
In German
- father's father = mother's father | Großvater = Opa
- father's mother = mother's mother | Großmutter = Oma

So in your list, it should be
- parent's parent | Großeltern

or maybe
- parent's parent | Großeltern (Großvater (Opa) **or** Großmutter (Oma))

but the existing line is definitely wrong
- parent's parent | Großeltern, Opa

**Comment by SamPassmore** [comment]
Ah I see. I misunderstood your first comment. 

I have changed this in the kinbank/varikin repository. It will filter through when the dataset is next updated.
