### ISSUE TITLE
metadata instead of forms and values for aust1271

### ISSUE THREAD

**Issue by OlenaShcherbakova** [kinbank/kinbank#130]
It seems like there is a problem with the Form and Value columns for aust1271 in the forms file: https://github.com/kinbank/kinbank/blob/master/kinbank/cldf/forms.csv. Metadata appears there instead of forms and values, e.g. "http://auslan.org.au/dictionary/words/brother-1.html" is in the value column.

This problem occurs when trying to access the file using:
read.delim(
      "https://raw.githubusercontent.com/kinbank/kinbank/master/kinbank/cldf/forms.csv",
      sep = ","
    )

**Comment by SamPassmore** [comment]
Hi Olena, 

This isn't a mistake. Auslan is a sign language, the website in the forms column shows a link to a video of the sign. 
It should work with read.csv.

Let me know if I've misunderstood. 

Sam
