### ISSUE TITLE
change morgan file names

### ISSUE THREAD

**Issue by SamPassmore** [kinbank/kinbank#15]
A non-urgent point - my backup system does not like special characters in the file name which is the case for a number of the raw parabank files (e.g. Morgan1871_Dakota\_Isauntie_dako1258.csv). 

Would altering those file names ruin anything for anyone?

**Comment by SimonGreenhill** [comment]
No, feel free!

(what backup system can't handle UTF-8??)

**Comment by SamPassmore** [comment]
Microsoft one drive! It's a nightmare but also the university pays for it.

**Comment by SamPassmore** [comment]
I realise now that even I change the data here, it will be rewritten every time the database is updated because the files are in the PB repo. 

In any case I have archived the Varikin repo - so more updates from our end!
