### ISSUE TITLE
Parameters: G & PP

### ISSUE THREAD

**Issue by SamPassmore** [kinbank/kinbank#2]
There are currently two parameters for grandparents in cldf/concepts.csv
l.387 G - Grandparent
l.441 PP - Parent's parent

I am not sure if this is a coding mistake in the creation of the concepts file or in the data. 
G within varikin refers to sibling and this is listed as a varikin concept.

**Comment by SimonGreenhill** [comment]
Oops, think this is my fault. I think it should be safe to simply rename the relevant row for G in concepts.tsv?

**Comment by SamPassmore** [comment]
Cool - this is what I thought but just wanted to double check. Will do this today!
