### ISSUE TITLE
waiw1244: Needs source checked

### ISSUE THREAD

**Issue by SamPassmore** [kinbank/kinbank#27]
Here the sibling terms appear to be described as sex of speaker, but aren't listed as such

e.g. https://ids.clld.org/valuesets/2-440-175

Since this data was taken from IDS, it might be worth finding another source for the data as well.

This book apparently has a good kinship section which might clear up any problems we have:

Fock, N. (1963). Waiwai: religion and society of an Amazonian tribe. National museum.

**Comment by maisieford** [comment]
Fixed this (PR #66 )
