### ISSUE TITLE
WZZD & WZZS

### ISSUE THREAD

**Issue by SamPassmore** [kinbank/kinbank#3]
These parameters came up from a coding bug from Sean's Uto-Aztecan work which we have removed from the varikin DB, but maybe not before the concepts file was made. 

It is not longer in the varikin lexibank format. 

So is it safe just to delete this from the concepts file?

**Comment by SimonGreenhill** [comment]
Ok, my last update seems to have removed these too -- but we still have mWZZD and mWZZS, are these ok?

**Comment by SimonGreenhill** [comment]
(note that the resulting parameters list in ./cldf/parameters.csv automatically removes any concepts that don't have any entries)

**Comment by SamPassmore** [comment]
ok - they don't exist in my most recent update on our side (which I literally just did)
So they should disappear with the next update. Will leave this open just to double check.

**Comment by SimonGreenhill** [comment]
all fixed!
