### ISSUE TITLE
restricted languages

### ISSUE THREAD

**Issue by SamPassmore** [kinbank/kinbank#8]
We have a number of languages from Claire Bowern's Austkin DB that she says is fine to use for analysis, but please check with her first about officially publishing them. They are all Pama- Nyungan languages. 

they are:

adny1235
alya1239
arab1267
badi1246
band1339
bayu1240
biri1256
darl1243
dhar1248
dhuw1249
dier1241
djam1256
djin1253
dyir1250
flin1247
gami1243
gugu1255
guma1253
guny1241
gupa1247
guri1247
jaru1254
kalk1246
kara1476
kari1304
kart1247
kaur1267
kuka1246
kuku1273
kumb1268
malg1242
marg1253
mart1256
mudb1240
muru1266
narr1259
ngaa1240
ngad1258
ngam1265
ngar1235
ngar1286
ngar1287
nhan1238
nyam1271
nyan1301
pint1250
pirr1240
pitj1243
pitt1247
rita1239
umpi1239
waga1260
waja1257
wang1290
wang1291
wanm1242
warl1254
warl1255
waru1264
waru1265
wikm1247
wira1262
wira1265
woiw1237
wong1246
wulg1239
yala1262
yand1253
yany1243
yidi1250
yind1247
yort1237
yugu1249
yulp1239

**Comment by SimonGreenhill** [comment]
Hmm, ok, can we ask Claire or should we remove these?

**Comment by SamPassmore** [comment]
I will send and email to see where we are at with this. My interpretation (which was via Catherine who dealt with Claire) was that this primarily referred to the publication of the dataset, so I don't think the public repo will be a problem as Austkin is open access anyway.

**Comment by SamPassmore** [comment]
Still no response from anyone at Austkin except Claire Bowern. Attaching email thread here for posterity:

> Dear all,
> I'm writing with a question about Austkin data access. Sam Passmore and I (in collaboration with Fiona Jordan and others) have been working on kinship term evolution in Australia - mostly Sam's work but a few aspects of it were in conjunction with me. Sam's project involves a database of kinship data, which also includes both Chirila data and AustKin data. Chirila includes Austkin1's terms, and we were wondering about permission to include Austkin data in the KinBank database (with due attribution of course). Would that be possible?
> All the best,
> Claire
>

**Comment by SamPassmore** [comment]
I never heard back from these people so I am closing the issue.
