### ISSUE TITLE
bawa_role_1968 error

### ISSUE THREAD

**Issue by SamPassmore** [kinbank/kinbank#80]
In kuma1273 the source bawa_role_1968 is not in sources.bib

also in this file there is bawa_role_1969 

These are possible excel errors from clicking and dragging down. 

They should all be 

bawa_role_1967

**Comment by JCalladine** [comment]
I put this language in, can confirm it's a click and drag error. have changed all to bawa_role_1967

**Comment by JCalladine** [comment]
also added bawa_role_1967 to source.bib
