### ISSUE TITLE
missing concepts from etc/concepts.csv

### ISSUE THREAD

**Issue by SamPassmore** [kinbank/kinbank#82]
These concepts are missing: 

mBC
mBCh
mZCh
mWBCh
mBC
mWFF
mWMF
fHMF
mWMM
fHMM
fHFM

**Comment by JCalladine** [comment]
Which data sheets/sources do these appear in? Because BCh seems like a strange denotation, is it meant to be mBCH, or just BC? I can put the other one's in straight away though

**Comment by SamPassmore** [comment]
You can search for where the concepts appear using the search function inside the file explorer I think.
(Or at least you can on my mac) 

Just navigate to the kinbank folder on your computer.

**Comment by JCalladine** [comment]
have pushed these concepts

**Comment by SamPassmore** [comment]
ok - you will also need to submit a pull request since I have already merged your previous one.
