### ISSUE TITLE
Missing sources from sources.bib

### ISSUE THREAD

**Issue by SamPassmore** [kinbank/kinbank#95]
snyman_introduction_1969

and 

lee_dobe_2013

are missing from the sources.bib file

**Comment by JCalladine** [comment]
these are in the KXA folder of zotero. I tried to copy and paste them in again - but there's something about my zotero or clipboard that means that the format gets jumbled, even though I've selected the right options. It might be better if somebody else puts them in?

**Comment by SimonGreenhill** [comment]
if you have a DOI, try using [doi2bib](https://www.doi2bib.org/) for something easily cut and pasteable 👍
