### ISSUE TITLE
Make datasets identifiable and citeable

### ISSUE THREAD

**Issue by SamPassmore** [kinbank/kinbank#99]
After discussion with Fiona and @jtbirchall , we are hoping to make the collection sets within Kinbank identifiable as separate entities (i.e. Varikin, Parabank, And Goeldi) with the goal of increasing the visibility of the work being performed outside big research institutes. 

At the moment, we have markers for Parabank and Varikin (as a result of the merging of github repos), and I have a list somewhere from Josh of languages collected by Goedli (reminder to me: it is on slack in a convo with Josh and Fiona 7th May 2020).

@SimonGreenhill, in SAILS and WALS, this appears to be done by adding a new table 'contributions' with a foriegn key into another table. Do you think I could apply that approach here relatively easily? I would guess the foreign key would go into languages or forms? Forms would be robust against groups collecting the same language I guess.

**Comment by SimonGreenhill** [comment]
Sure. The contributors table is generally used more for person level contribs (e.g. X added data for A, B, C) but you could do it this way if you wanted. 

Alternatively, we are already tracking this information in the 'project' column of [languages.csv](https://github.com/kinbank/kinbank/blob/master/kinbank/cldf/languages.csv) so could just keep using that.

(@xrotwang -- any comments?)

**Comment by xrotwang** [comment]
In the `clld` data model, there's a `Contribution` entity. This is supposed to aggregate data based on what should be a "citable unit" - not necessarily based on contributors as persons. So I'd guess an equivalent table for the CLDF data would be the ideal solution here - and would translate well in case the data is goin to be presented in a clld app at some point.

**Comment by SamPassmore** [comment]
@xrotwang can I add this in the current state of CLDF, or are you suggesting CLDF needs a new entity type? 

I tried changing the cldf-metadata.json file by hand, but this didn't seem to work. Which I guess in retrospect I should have expected.  

@SimonGreenhill I don't understand how the etc/ folder links with the cldf command in the Makefile. Is this a folder than pycldf knows to look for? I can't see it referenced otherwise. This is where I have kept the contributions file at the moment.

**Comment by xrotwang** [comment]
I'll have a look tomorrow.

SamPassmore <notifications@github.com> schrieb am Mo., 26. Okt. 2020, 18:56:

**Comment by xrotwang** [comment]
At the risk of making you mad, my proposal here would be to split the data into three repositories.
I know, you spent effort combining the data, but this effort wouldn't be wasted, because it would make sure the three repositories have the same structure.

With this setup, each dataset would get its own DOI (and archiving and longterm accessibility) from Zenodo, and a central web app could make the aggregated data browsable. That's the strategy we basically settled for for **all** our current projects, be it Dictionaria or Lexibank or Tsammalex or D-PLACE.

**Comment by SimonGreenhill** [comment]
(╯°□°）╯︵ ┻━┻

but yeah, that probably makes sense.

**Comment by SamPassmore** [comment]
ヽ(ಠ_ಠ)ノ

Ok - so within the kinbank org make a repository for each dataset?

Should I split the CLDF dataset? (i.e. each repo is only cldf dataset) 
Or subset the raw files, and each repo builds a seperate cldf dataset? 

It looks like in Lexibank it is the second option, so I guess that is likely going to apply here also?

**Comment by xrotwang** [comment]
I can help with this, too - but don't have any permissions for this org now.

SamPassmore <notifications@github.com> schrieb am Di., 27. Okt. 2020, 17:34:

**Comment by SamPassmore** [comment]
Sorry - my emoticon was ungenerous! (I spent too long looking through the emoticon list on wikipedia).  
Thanks for your suggestion! 

I have my viva in just over a week, so I will mull on this for a bit before planning ahead!

**Comment by SamPassmore** [comment]
@xrotwang Just getting my head around why you think splitting into different repos will be best. 

I see in grambank they have the contributions table. To me this seems like a sufficient solution for us here. But is the reason we can't use that because the contributions table type will not be included in the cldfbench creation of kinbank? (whereas grambank appears to be static in the grambank-cldf repo - although I guess the creation might be being done elsewhere). 

If there is no technical reason for doing it this way, presumably you were suggesting it for the archiving / doi benefits?

**Comment by xrotwang** [comment]
@SamPassmore If visibility of the collections in the web app is all you are after, then a Grambank-like solution should be ok. But the citable dataset is probably going to be the dataset as archived (and provided with a DOI) on Zenodo. So if you want to have separate, DOI-citable datasets for each collection **and** use the github-Zenodo bridge, separate repositories would be required.

**Comment by SamPassmore** [comment]
Sorry for having this on the back-burner. 

I had a conversation with Simon via email, which convinced me that splitting is the best. 

I can do this, but wanted to get your opinion on the best approach.
I thought the easiest approach would be to replicate the current repo three times, and then get a 1-time script to delete langauges as necessary. 

Splitting parabank from varikin is easy enough since it is in the society ID, but the Goeldi records are held under varikin because I was managing the data at the time the datasets were originally merged. The records from Goeldi are on a file that I have, so I can split those out from varikin. 

I worry that this isn't very reproducible though, but then maybe it doesn't need to be.
